### ISSUE TITLE
[BUG] Using fs-extra throws error

### ISSUE THREAD

**Issue by JackDallas** [HaveAGitGat/Tdarr_Plugins#47]
When running a plugin using the fs-extra module an error is thrown trying to invoke it:
```
ShellJSInternalError: ENOENT: no such file or directory, open '/tmp/shelljs_029d62444a9ccb8665a2'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at execSync (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/shelljs/src/exec.js:89:17)
    at Object._exec (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/shelljs/src/exec.js:205:12)
    at Object.exec (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/shelljs/src/common.js:335:23)
    at process.on (/home/Tdarr/Tdarr/bundle/programs/server/assets/app/worker1.js:148:19)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
{ Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.plugin (/home/Tdarr/Tdarr/bundle/programs/server/assets/app/plugins/Community/Tdarr_Plugin_z18s_rename_files_based_on_codec.js:25:19)
    at getNewTask (server/main.js:3010:51)
    at server/main.js:2389:11
    at runWithEnvironment (packages/meteor.js:1286:24) code: 'MODULE_NOT_FOUND' }
Server: Worker _7r0ts39 requesting item. Nothing to process for this worker.
```
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_z18s_rename_files_based_on_codec.js#L25

cc: @Migz93

**Comment by JackDallas** [comment]
azcom on Discord has confirmed this issue is present on windows as well

**Comment by azcom** [comment]
I have got it to work by copying the "fs-extra" folder from "\programs\server\npm\node_modules" into "\programs\server\node_modules"

**Comment by HaveAGitGat** [comment]
Fixed
