### ISSUE TITLE
`ffmpegCommandExecute` Flow Plugin Does Not Log Return Code and Error Log on Failure

### ISSUE THREAD

**Issue by sdwilsh** [HaveAGitGat/Tdarr_Plugins#588]
The [code for this plugin will note that the command failed](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.ts#L175-L178), but it doesn't print out any information for someone to debug it.  It looks like the `CLI` helper can provide the return code and the log (it might even log the full log today, but I can't figure out where the config is that would allow me to activate [this block of code](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/cliUtils.ts#L343-L345)), and that would be great to show in the report when a job fails so the end user can debug the issue and correct it.

Current output looks like this:
```
2024-01-22T22:40:46.650Z FoB9ba931:Node[worker01]:Worker[young-yeti]:Running FFmpeg failed
2024-01-22T22:40:46.650Z FoB9ba931:Node[worker01]:Worker[young-yeti]:[-error-]
2024-01-22T22:40:46.650Z FoB9ba931:Node[worker01]:Worker[young-yeti]:Error: FFmpeg failed
2024-01-22T22:40:46.651Z FoB9ba931:Node[worker01]:Worker[young-yeti]:"FFmpeg failed"
2024-01-22T22:40:46.651Z FoB9ba931:Node[worker01]:Worker[young-yeti]:"Error: FFmpeg failed\n at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:192:27\n at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:33:23)\n at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:14:53)\n at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:5:58)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2024-01-22T22:40:46.651Z FoB9ba931:Node[worker01]:Worker[young-yeti]:Flow has failed
```

**Comment by sdwilsh** [comment]
After seeing https://github.com/HaveAGitGat/Tdarr/issues/936, I decided to add more memory to the worker, and that seems to have fixed my underlying issue.  The logs that tdarr gave me from this flow plugin did not help me actually debug this, unfortunately.
