### ISSUE TITLE
BUG: Migz1FFMPEG, Subtitle codec 0 is not supported, Unknown/unsupported AVCodecID S_TEXT/WEBVTT

### ISSUE THREAD

**Issue by Jacob-Lasky** [HaveAGitGat/Tdarr_Plugins#703]
I am running into an error while transcoding to h265 using the Migz1FFMPEG plugin: `Unknown/unsupported AVCodecID S_TEXT/WEBVTT` and `Subtitle codec 0 is not supported` . I believe this is similar to https://github.com/HaveAGitGat/Tdarr_Plugins/issues/619 but this is a different plugin (hence the separate bug report).

<details>
  <summary>
    FFPMEG Output
  </summary>
    <pre>
1: 2024-10-15T09:22:12.327Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:[Step W03] [C7] [Flow 1] Running Community plugin: 1.0.0: runClassicTranscodePlugin: Classic: Transcode to h265
2: 2024-10-15T09:22:12.328Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Scanning original library file
3: 2024-10-15T09:22:12.329Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:{
4: 2024-10-15T09:22:12.329Z "exifToolScan": true,
5: 2024-10-15T09:22:12.329Z "mediaInfoScan": false,
6: 2024-10-15T09:22:12.329Z "closedCaptionScan": false
7: 2024-10-15T09:22:12.329Z }
8: 2024-10-15T09:22:12.330Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Loading source file: "/data/media/tv/South Park (1997) {tvdb-75897}/Season 02/South Park (1997) - S02E03 - Ikes Wee Wee [MAX WEBDL-1080p][EAC3 5.1][x264]-AndreMor.mkv"
9: 2024-10-15T09:22:12.331Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Scanning source file: "/data/media/tv/South Park (1997) {tvdb-75897}/Season 02/South Park (1997) - S02E03 - Ikes Wee Wee [MAX WEBDL-1080p][EAC3 5.1][x264]-AndreMor.mkv"
10: 2024-10-15T09:22:12.333Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Scan types: {
11: 2024-10-15T09:22:12.333Z "exifToolScan": true,
12: 2024-10-15T09:22:12.333Z "mediaInfoScan": false,
13: 2024-10-15T09:22:12.333Z "closedCaptionScan": false
14: 2024-10-15T09:22:12.333Z }
15: 2024-10-15T09:22:12.334Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Using cached scan results
16: 2024-10-15T09:22:12.335Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Loaded plugin inputs: {
17: 2024-10-15T09:22:12.335Z "pluginSourceId": "Community:Tdarr_Plugin_MC93_Migz1FFMPEG",
18: 2024-10-15T09:22:12.335Z "container": "mkv",
19: 2024-10-15T09:22:12.335Z "enable_10bit": "false",
20: 2024-10-15T09:22:12.335Z "enable_bframes": "false",
21: 2024-10-15T09:22:12.335Z "force_conform": "true"
22: 2024-10-15T09:22:12.335Z }
23: 2024-10-15T09:22:12.336Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:No depedencies to install for Community:Tdarr_Plugin_MC93_Migz1FFMPEG
24: 2024-10-15T09:22:12.337Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Scanning files using Node
25: 2024-10-15T09:22:13.338Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:{
26: 2024-10-15T09:22:13.338Z "processFile": true,
27: 2024-10-15T09:22:13.338Z "preset": "-c:v h264_cuvid, -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 1426k -minrate 998k -maxrate 1853k -bufsize 2853k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d ",
28: 2024-10-15T09:22:13.338Z "handBrakeMode": false,
29: 2024-10-15T09:22:13.338Z "FFmpegMode": true,
30: 2024-10-15T09:22:13.338Z "reQueueAfter": true,
31: 2024-10-15T09:22:13.338Z "infoLog": "Container for output selected as mkv. Current bitrate = 2853 Bitrate settings: Target = 1426 Minimum = 998 Maximum = 1853 File is not hevc or vp9. Transcoding. ",
32: 2024-10-15T09:22:13.338Z "container": ".mkv"
33: 2024-10-15T09:22:13.338Z }
34: 2024-10-15T09:22:13.339Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:{
35: 2024-10-15T09:22:13.339Z "processFile": true,
36: 2024-10-15T09:22:13.339Z "preset": "-c:v h264_cuvid, -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 1426k -minrate 998k -maxrate 1853k -bufsize 2853k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d ",
37: 2024-10-15T09:22:13.339Z "handBrakeMode": false,
38: 2024-10-15T09:22:13.339Z "FFmpegMode": true,
39: 2024-10-15T09:22:13.339Z "reQueueAfter": true,
40: 2024-10-15T09:22:13.339Z "infoLog": "Container for output selected as mkv. Current bitrate = 2853 Bitrate settings: Target = 1426 Minimum = 998 Maximum = 1853 File is not hevc or vp9. Transcoding. ",
41: 2024-10-15T09:22:13.339Z "container": ".mkv",
42: 2024-10-15T09:22:13.339Z "ffmpegMode": true,
43: 2024-10-15T09:22:13.339Z "cliToUse": "ffmpeg"
44: 2024-10-15T09:22:13.339Z }
45: 2024-10-15T09:22:13.340Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Running tdarr-ffmpeg -c:v h264_cuvid -i /data/media/tv/South Park (1997) {tvdb-75897}/Season 02/South Park (1997) - S02E03 - Ikes Wee Wee [MAX WEBDL-1080p][EAC3 5.1][x264]-AndreMor.mkv -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 1426k -minrate 998k -maxrate 1853k -bufsize 2853k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d /data/others/tdarr-cache/tdarr-workDir-node-Ddjo7cU3_-worker-only-oryx-ts-1728998524560/1728998529692/South Park (1997) - S02E03 - Ikes Wee Wee [MAX WEBDL-1080p][EAC3 5.1][x264]-AndreMor.mkv
46: 2024-10-15T09:22:13.341Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:CLI error code: 1
47: 2024-10-15T09:22:13.342Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
48: 2024-10-15T09:22:13.342Z built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
49: 2024-10-15T09:22:13.342Z configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
50: 2024-10-15T09:22:13.342Z libavutil 58. 2.100 / 58. 2.100
51: 2024-10-15T09:22:13.342Z libavcodec 60. 3.100 / 60. 3.100
52: 2024-10-15T09:22:13.342Z libavformat 60. 3.100 / 60. 3.100
53: 2024-10-15T09:22:13.342Z libavdevice 60. 1.100 / 60. 1.100
54: 2024-10-15T09:22:13.342Z libavfilter 9. 3.100 / 9. 3.100
55: 2024-10-15T09:22:13.342Z libswscale 7. 1.100 / 7. 1.100
56: 2024-10-15T09:22:13.342Z libswresample 4. 10.100 / 4. 10.100
57: 2024-10-15T09:22:13.342Z libpostproc 57. 1.100 / 57. 1.100
58: 2024-10-15T09:22:13.342Z [matroska,webm @ 0x55f7479d88c0] Unknown/unsupported AVCodecID S_TEXT/WEBVTT.
59: 2024-10-15T09:22:13.342Z Last message repeated 1 times
60: 2024-10-15T09:22:13.342Z [matroska,webm @ 0x55f7479d88c0] Could not find codec parameters for stream 3 (Subtitle: none): unknown codec
61: 2024-10-15T09:22:13.342Z Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
62: 2024-10-15T09:22:13.342Z [matroska,webm @ 0x55f7479d88c0] Could not find codec parameters for stream 4 (Subtitle: none): unknown codec
63: 2024-10-15T09:22:13.342Z Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
64: 2024-10-15T09:22:13.342Z Input #0, matroska,webm, from '/data/media/tv/South Park (1997) {tvdb-75897}/Season 02/South Park (1997) - S02E03 - Ikes Wee Wee [MAX WEBDL-1080p][EAC3 5.1][x264]-AndreMor.mkv':
65: 2024-10-15T09:22:13.342Z Metadata:
66: 2024-10-15T09:22:13.342Z title : South Park S02E03 - Ike's Wee Wee (1998)
67: 2024-10-15T09:22:13.342Z encoder : libebml v1.4.2 + libmatroska v1.6.4
68: 2024-10-15T09:22:13.342Z creation_time : 2024-08-27T20:29:29.000000Z
69: 2024-10-15T09:22:13.342Z Duration: 00:22:02.90, start: 0.000000, bitrate: 2992 kb/s
70: 2024-10-15T09:22:13.342Z Stream #0:0(zxx): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
71: 2024-10-15T09:22:13.342Z Metadata:
72: 2024-10-15T09:22:13.342Z title : MPEG4 AVC / 2547 KiBs / 23.976 fps / 1.78:1
73: 2024-10-15T09:22:13.342Z BPS : 2608438
74: 2024-10-15T09:22:13.342Z DURATION : 00:22:02.822000000
75: 2024-10-15T09:22:13.342Z NUMBER_OF_FRAMES: 31716
76: 2024-10-15T09:22:13.342Z NUMBER_OF_BYTES : 431312455
77: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
78: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_DATE_UTC: 2024-08-27 20:29:29
79: 2024-10-15T09:22:13.342Z _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
80: 2024-10-15T09:22:13.342Z Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s (default)
81: 2024-10-15T09:22:13.342Z Metadata:
82: 2024-10-15T09:22:13.342Z title : English / Dolby Digital Plus / 5.1 / 48.000 kHz / 250 KiBs
83: 2024-10-15T09:22:13.342Z BPS : 256000
84: 2024-10-15T09:22:13.342Z DURATION : 00:22:02.848000000
85: 2024-10-15T09:22:13.342Z NUMBER_OF_FRAMES: 41339
86: 2024-10-15T09:22:13.342Z NUMBER_OF_BYTES : 42331136
87: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
88: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_DATE_UTC: 2024-08-27 20:29:29
89: 2024-10-15T09:22:13.342Z _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
90: 2024-10-15T09:22:13.342Z Stream #0:2(spa): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
91: 2024-10-15T09:22:13.342Z Metadata:
92: 2024-10-15T09:22:13.342Z title : Spanish / AAC / 2.0 / 48.000 kHz / 122 KiBs
93: 2024-10-15T09:22:13.342Z BPS : 125375
94: 2024-10-15T09:22:13.342Z DURATION : 00:22:02.901000000
95: 2024-10-15T09:22:13.342Z NUMBER_OF_FRAMES: 62011
96: 2024-10-15T09:22:13.342Z NUMBER_OF_BYTES : 20732345
97: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
98: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_DATE_UTC: 2024-08-27 20:29:29
99: 2024-10-15T09:22:13.342Z _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
100: 2024-10-15T09:22:13.342Z Stream #0:3(eng): Subtitle: none
101: 2024-10-15T09:22:13.342Z Metadata:
102: 2024-10-15T09:22:13.342Z title : English (United States)
103: 2024-10-15T09:22:13.342Z BPS : 216
104: 2024-10-15T09:22:13.342Z DURATION : 00:12:37.087000000
105: 2024-10-15T09:22:13.342Z NUMBER_OF_FRAMES: 2
106: 2024-10-15T09:22:13.342Z NUMBER_OF_BYTES : 20510
107: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
108: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_DATE_UTC: 2024-08-27 20:29:29
109: 2024-10-15T09:22:13.342Z _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
110: 2024-10-15T09:22:13.342Z Stream #0:4(spa): Subtitle: none
111: 2024-10-15T09:22:13.342Z Metadata:
112: 2024-10-15T09:22:13.342Z title : Spanish (Latin America)
113: 2024-10-15T09:22:13.342Z BPS : 232
114: 2024-10-15T09:22:13.342Z DURATION : 00:12:36.287000000
115: 2024-10-15T09:22:13.342Z NUMBER_OF_FRAMES: 3
116: 2024-10-15T09:22:13.342Z NUMBER_OF_BYTES : 22014
117: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
118: 2024-10-15T09:22:13.342Z _STATISTICS_WRITING_DATE_UTC: 2024-08-27 20:29:29
119: 2024-10-15T09:22:13.342Z _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
120: 2024-10-15T09:22:13.342Z Stream mapping:
121: 2024-10-15T09:22:13.342Z Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))
122: 2024-10-15T09:22:13.342Z Stream #0:1 -> #0:1 (copy)
123: 2024-10-15T09:22:13.342Z Stream #0:2 -> #0:2 (copy)
124: 2024-10-15T09:22:13.342Z Stream #0:3 -> #0:3 (copy)
125: 2024-10-15T09:22:13.342Z Stream #0:4 -> #0:4 (copy)
126: 2024-10-15T09:22:13.342Z Press [q] to stop, [?] for help
127: 2024-10-15T09:22:13.342Z [matroska @ 0x55f747a22540] Subtitle codec 0 is not supported.
128: 2024-10-15T09:22:13.342Z [out#0/matroska @ 0x55f747b88b80] Could not write header (incorrect codec parameters ?): Function not implemented
129: 2024-10-15T09:22:13.342Z [vost#0:0/hevc_nvenc @ 0x55f747a1e940] Error initializing output stream:
130: 2024-10-15T09:22:13.342Z Conversion failed!
131: 2024-10-15T09:22:13.342Z
132: 2024-10-15T09:22:13.343Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:CLI tdarr-ffmpeg exited with code: 1
133: 2024-10-15T09:22:13.344Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:[-error-]
134: 2024-10-15T09:22:13.345Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Running tdarr-ffmpeg failed
135: 2024-10-15T09:22:13.346Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Error: Running tdarr-ffmpeg failed
136: 2024-10-15T09:22:13.347Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:"Running tdarr-ffmpeg failed"
137: 2024-10-15T09:22:13.348Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:"Error: Running tdarr-ffmpeg failed at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:227:27 at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:33:23) at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:14:53) at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:5:58) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
138: 2024-10-15T09:22:13.349Z 02A3ds1oE:Node[tdarrNode_UnRAID1]:Worker[only-oryx]:Flow has failed
    </pre>
</details>

**Comment by strich** [comment]
This is still a problem.

**Comment by Puyodead1** [comment]
ughhhhh, its pissing me off
