### ISSUE TITLE
QSV Fails: Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'

### ISSUE THREAD

**Issue by phoenixaus** [HaveAGitGat/Tdarr_Plugins#713]
PC Details:

Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: NUC14RVB
        Version: 60AS0080-MB0A01
        Serial Number: *******

GPU: 
 VGA compatible controller: Intel Corporation Meteor Lake-P [Intel Arc Graphics] (rev 08) (prog-if 00 [VGA controller])
        DeviceName: Onboard - Video
        Subsystem: ASUSTeK Computer Inc. Meteor Lake-P [Intel Arc Graphics]
        Flags: bus master, fast devsel, latency 0, IRQ 212, IOMMU group 0
        Memory at 5017000000 (64-bit, prefetchable) [size=16M]
        Memory at 4000000000 (64-bit, prefetchable) [size=256M]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit+
        Capabilities: [d0] Power Management version 3
        Capabilities: [100] Null
        Capabilities: [110] Process Address Space ID (PASID)
        Capabilities: [200] Address Translation Service (ATS)
        Capabilities: [420] Physical Resizable BAR
        Capabilities: [320] Single Root I/O Virtualization (SR-IOV)
        Capabilities: [400] Latency Tolerance Reporting
        Kernel driver in use: i915
        Kernel modules: i915, xe

Mainly on .TS conversions, I'm getting this error:
`2024-11-06T13:40:45.399Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:[Step W03] [C17] [Recorded TV] Running Community plugin: 1.0.0: ffmpegCommandExecute: Execute

2

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Scanning original library file

3

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:{

4

2024-11-06T13:40:45.400Z "exifToolScan": true,

5

2024-11-06T13:40:45.400Z "mediaInfoScan": false,

6

2024-11-06T13:40:45.400Z "closedCaptionScan": false

7

2024-11-06T13:40:45.400Z }

8

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:File found locally

9

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Loading source file: "/tmp/tdarr-workDir2-uBDs2YEMi/1730864284831/Creek To Coast S22E04 Series 22, Episode 4.ts"

10

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Scanning source file: "/tmp/tdarr-workDir2-uBDs2YEMi/1730864284831/Creek To Coast S22E04 Series 22, Episode 4.ts"

11

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Scan types: {

12

2024-11-06T13:40:45.400Z "exifToolScan": true,

13

2024-11-06T13:40:45.400Z "mediaInfoScan": false,

14

2024-11-06T13:40:45.400Z "closedCaptionScan": false

15

2024-11-06T13:40:45.400Z }

16

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Using cached scan results

17

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Loaded plugin inputs: {}

18

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:{"spawnArgs":["-y","-hwaccel","qsv","-i","/tmp/tdarr-workDir2-uBDs2YEMi/1730864284831/Creek To Coast S22E04 Series 22, Episode 4.ts","-map","0:0","-vf","scale=1280:-2","-b:v:0","2500k","-c:0","hevc_qsv","-qp","25","-preset","fast","-map","0:1","-c:1","copy","-fflags","+genpts","/tmp/tdarr-workDir2-uBDs2YEMi/1730864442758/Creek To Coast S22E04 Series 22, Episode 4.mkv"],"outputFilePath":"/tmp/tdarr-workDir2-uBDs2YEMi/1730864442758/Creek To Coast S22E04 Series 22, Episode 4.mkv"}

19

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Processing file

20

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Running tdarr-ffmpeg -y -hwaccel qsv -i /tmp/tdarr-workDir2-uBDs2YEMi/1730864284831/Creek To Coast S22E04 Series 22, Episode 4.ts -map 0:0 -vf scale=1280:-2 -b:v:0 2500k -c:0 hevc_qsv -qp 25 -preset fast -map 0:1 -c:1 copy -fflags +genpts /tmp/tdarr-workDir2-uBDs2YEMi/1730864442758/Creek To Coast S22E04 Series 22, Episode 4.mkv

21

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:CLI error code: 1

22

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Running FFmpeg failed

23

2024-11-06T13:40:45.400Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:CLI tdarr-ffmpeg exited with code: 1

24

2024-11-06T13:40:45.401Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers

25

2024-11-06T13:40:45.401Z built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)

26

2024-11-06T13:40:45.401Z configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc

27

2024-11-06T13:40:45.401Z libavutil 58. 2.100 / 58. 2.100

28

2024-11-06T13:40:45.401Z libavcodec 60. 3.100 / 60. 3.100

29

2024-11-06T13:40:45.401Z libavformat 60. 3.100 / 60. 3.100

30

2024-11-06T13:40:45.401Z libavdevice 60. 1.100 / 60. 1.100

31

2024-11-06T13:40:45.401Z libavfilter 9. 3.100 / 9. 3.100

32

2024-11-06T13:40:45.401Z libswscale 7. 1.100 / 7. 1.100

33

2024-11-06T13:40:45.401Z libswresample 4. 10.100 / 4. 10.100

34

2024-11-06T13:40:45.401Z libpostproc 57. 1.100 / 57. 1.100

35

2024-11-06T13:40:45.401Z WARNING: defaulting hwaccel_output_format to qsv for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format qsv".

36

2024-11-06T13:40:45.401Z Input #0, mpegts, from '/tmp/tdarr-workDir2-uBDs2YEMi/1730864284831/Creek To Coast S22E04 Series 22, Episode 4.ts':

37

2024-11-06T13:40:45.401Z Duration: 00:38:14.55, start: 1.412900, bitrate: 6763 kb/s

38

2024-11-06T13:40:45.401Z Program 1

39

2024-11-06T13:40:45.401Z Metadata:

40

2024-11-06T13:40:45.401Z service_name : Service01

41

2024-11-06T13:40:45.401Z service_provider: FFmpeg

42

2024-11-06T13:40:45.401Z Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn

43

2024-11-06T13:40:45.401Z Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 195 kb/s

44

2024-11-06T13:40:45.401Z libva info: VA-API version 1.21.0

45

2024-11-06T13:40:45.401Z libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so

46

2024-11-06T13:40:45.401Z libva info: Found init function __vaDriverInit_1_21

47

2024-11-06T13:40:45.401Z libva info: va_openDriver() returns 0

48

2024-11-06T13:40:45.401Z libva info: VA-API version 1.21.0

49

2024-11-06T13:40:45.401Z libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so

50

2024-11-06T13:40:45.401Z libva info: Found init function __vaDriverInit_1_21

51

2024-11-06T13:40:45.401Z libva info: va_openDriver() returns 0

52

2024-11-06T13:40:45.401Z Stream mapping:

53

2024-11-06T13:40:45.401Z Stream #0:0 -> #0:0 (h264 (h264_qsv) -> hevc (hevc_qsv))

54

2024-11-06T13:40:45.401Z Stream #0:1 -> #0:1 (copy)

55

2024-11-06T13:40:45.401Z Press [q] to stop, [?] for help

56

2024-11-06T13:40:45.401Z Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'

57

2024-11-06T13:40:45.401Z Error reinitializing filters!

58

2024-11-06T13:40:45.401Z Failed to inject frame into filter network: Function not implemented

59

2024-11-06T13:40:45.401Z Error while processing the decoded data for stream #0:0

60

2024-11-06T13:40:45.401Z Conversion failed!

61

2024-11-06T13:40:45.401Z

62

2024-11-06T13:40:45.401Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:[-error-]

63

2024-11-06T13:40:45.401Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:"Error: FFmpeg failed\n at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:195:27\n at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:33:23)\n at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:14:53)\n at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandExecute/1.0.0/index.js:5:58)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

64

2024-11-06T13:40:45.401Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:"FFmpeg failed"

65

2024-11-06T13:40:45.401Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Error: FFmpeg failed

66

2024-11-06T13:40:45.401Z uBDs2YEMi:Node[Docker_server]:Worker[fine-flies]:Flow has failed`

**Comment by TheFrisbeeNinja** [comment]
I'm having this same problem, specifically on workflows that use the "Set Video Resolution" plugin. The plugin is adding 

**-vf scale=1920:-2**

 to the output arguments, but if you are using the QSV accelerator is should be
 
 **-vf scale_qsv=w=1920:h=1080**
 
 I don't know enough about the plugin system to know if it can be made hwaccel aware, but using a "Custom Argument" plugin to do the scaling instead of the "Set Video Resolution" plugin has resolved this issue for me.

**Comment by gdtms247** [comment]
Creating a local copy of "set video resolution" flow plugin and changing the argument to "-vf scale_qsv=w=" and the frame size fixed my QSV transcode, thanks @TheFrisbeeNinja!!

Failed:
[K9ynMgyOZ-log.txt](https://github.com/user-attachments/files/18811651/K9ynMgyOZ-log.txt)
Success: 
[xAK1zfcpj-log.txt](https://github.com/user-attachments/files/18811655/xAK1zfcpj-log.txt)

**Comment by gdtms247** [comment]
Doesn't appear this is 100% successful I still have random examples fail after changing the scale argument. Working on importing all prior media after storage update, will try and do some testing over the next few weeks and report back.

**Comment by HaveAGitGat** [comment]
Fixed by #791
