### ISSUE TITLE
HandbrakeCLI in Flow fails with error code null for remux 2160p movies

### ISSUE THREAD

**Issue by Sle3perX** [HaveAGitGat/Tdarr_Plugins#715]
I have set up Tdarr with docker compose with the combined use of the server and node (in one container) but also as a docker compose server and node as two containers. The error also occurs with a node directly installed my jailmaker instance on TrueNAS Scale.

Im using an HandbrakeCLI profile with SVT-AV1 and Opus encoding and different RF settings for 720p/1080p/2160p.

When the node on my TrueNAS encodes the movies in Remux quality in 2160p with up to 120 GB per file the HandbrakeCLI fails every time between 0-5%.

When the job is send to my node set up on my Windows 11 the job runs correctly and finished successfully.

Is there a way to get more specific info from HandbrakeCLI why the job fails?

`2024-11-10T20:44:06.466Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:CLI HandBrakeCLI exited with code: null

27

2024-11-10T20:44:06.466Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:Running HandBrake failed

28

2024-11-10T20:44:06.466Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:[-error-]

29

2024-11-10T20:44:06.466Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:Error: Running HandBrake failed

30

2024-11-10T20:44:06.466Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:"Error: Running HandBrake failed\n at /root/tdarr-node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/handbrake/handbrakeCustomArguments/2.0.0/index.js:207:27\n at step (/root/tdarr-node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/handbrake/handbrakeCustomArguments/2.0.0/index.js:33:23)\n at Object.next (/root/tdarr-node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/handbrake/handbrakeCustomArguments/2.0.0/index.js:14:53)\n at fulfilled (/root/tdarr-node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/handbrake/handbrakeCustomArguments/2.0.0/index.js:5:58)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

31

2024-11-10T20:44:06.467Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:"Running HandBrake failed"

32

2024-11-10T20:44:06.467Z KwTXqEOnB:Node[Jailmaker Node]:Worker[yummy-yeti]:Flow has failed`

**Comment by rgreen83** [comment]
In the staging section there is the option to "Log full FFmpeg/HandBrake output:" have you tried that? Also I would think the most likely problem would be your container lacking the required resources for the job.
